name: kapi
description: "Kapi – khallaf Api test: a focused Windows desktop API testing tool."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.7

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icons/kapi_icon.png"
    icon_size: 256

msix_config:
  display_name: Khallaf API Tester
  publisher_display_name: a1systems
  identity_name: a1systems.KhallafAPITester
  publisher: CN=4B16C474-01ED-49AC-8656-4BDC0A85089B
  msix_version: 1.0.0.0
  logo_path: assets/icons/kapi_icon.png
  store: true
  output_path: build/windows/x64/runner/Release
  output_name: KhallafAPITester
  languages: en-us
  capabilities: internetClient